FROM golang:1.26.6-alpine@sha256:3889b425f035be855a72fb4755265311293b6d414521f0a519d819df32222d83 AS build

ARG LOKI_COMMIT=b318f2829f0ae2094ab3a1e90780450e9e4b03be
ARG LOKI_SOURCE_SHA256=c9f0a926613e30615807c21d32fbc8956449b9aa519fab1024bc59f40f80879d

WORKDIR /src
RUN wget -qO source.tar.gz \
      "https://github.com/grafana/loki/archive/${LOKI_COMMIT}.tar.gz" \
  && echo "${LOKI_SOURCE_SHA256}  source.tar.gz" | sha256sum -c - \
  && tar -xzf source.tar.gz --strip-components=1 \
  && rm source.tar.gz

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
  success=false; \
  for attempt in 1 2 3; do \
    if go get \
        golang.org/x/crypto@v0.55.0 \
        golang.org/x/mod@v0.40.0 \
        golang.org/x/text@v0.41.0 \
        google.golang.org/grpc@v1.83.1 \
      && go mod tidy \
      && go mod vendor; then \
      success=true; \
      break; \
    fi; \
    echo "Go dependency transport failure; retrying (${attempt}/3)" >&2; \
    sleep $((attempt * 5)); \
  done; \
  test "${success}" = true \
  && test "$(go list -m -f '{{.Version}}' golang.org/x/crypto)" = "v0.55.0" \
  && test "$(go list -m -f '{{.Version}}' golang.org/x/mod)" = "v0.40.0" \
  && test "$(go list -m -f '{{.Version}}' golang.org/x/text)" = "v0.41.0" \
  && test "$(go list -m -f '{{.Version}}' google.golang.org/grpc)" = "v1.83.1"

ARG VERSION=3.7.4-phase6.1
ARG REVISION=b318f282
ARG BUILD_DATE=2026-07-29T00:00:00Z
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
  CGO_ENABLED=0 go build -trimpath -tags netgo \
    -ldflags="-extldflags '-static' -s -w \
      -X github.com/grafana/loki/v3/pkg/util/build.Branch=phase6-security-patch \
      -X github.com/grafana/loki/v3/pkg/util/build.Version=${VERSION} \
      -X github.com/grafana/loki/v3/pkg/util/build.Revision=${REVISION} \
      -X github.com/grafana/loki/v3/pkg/util/build.BuildUser=gis-release \
      -X github.com/grafana/loki/v3/pkg/util/build.BuildDate=${BUILD_DATE}" \
    -o /out/loki ./cmd/loki

FROM grafana/loki:3.7.4@sha256:87f0a067673756a3cede1bcbf0c74875f7df9b09fddb53e399d0c576f756cfcc

COPY --from=build /out/loki /usr/bin/loki
